import { existsSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig, loadEnv } from "vite";
import type { Plugin } from "vite";
import { devtools } from "@tanstack/devtools-vite";

import { tanstackStart } from "@tanstack/react-start/plugin/vite";

import viteReact from "@vitejs/plugin-react";
import { nitro } from "nitro/vite";
import tailwindcss from "@tailwindcss/vite";

/* The P7 "CNN Lab" reads pre-built dataset assets from public/datasets/. They are
   generated by `node scripts/build-datasets.mjs`, NOT at build time. This guard
   refuses to start the dev server or build if any of the four datasets is missing
   or isn't the expected 2000-train + 200-validation split, so a mis-built or
   absent asset fails loudly with an actionable message instead of the net
   silently training on nothing/garbage. */
const P7_DATASET_IDS = ["mnist", "fashion", "kmnist", "cifar10"];

function verifyP7Datasets(): void {
    const root = dirname(fileURLToPath(import.meta.url));
    const dir = join(root, "public", "datasets");
    const problems: string[] = [];
    for (const id of P7_DATASET_IDS) {
        const jsonPath = join(dir, `${id}.json`);
        const binPath = join(dir, `${id}.bin.gzip`);
        if (!existsSync(jsonPath) || !existsSync(binPath)) {
            problems.push(`${id}: missing ${id}.json and/or ${id}.bin.gzip`);
            continue;
        }
        if (statSync(binPath).size === 0) {
            problems.push(`${id}: ${id}.bin.gzip is empty`);
            continue;
        }
        let manifest: { trainN?: number; valN?: number };
        try {
            manifest = JSON.parse(readFileSync(jsonPath, "utf8"));
        } catch (e) {
            problems.push(
                `${id}: ${id}.json is not valid JSON (${(e as Error).message})`
            );
            continue;
        }
        if (manifest.trainN !== 2000 || manifest.valN !== 200) {
            problems.push(
                `${id}: wrong split (trainN=${manifest.trainN}, valN=${manifest.valN}; expected 2000 + 200)`
            );
        }
    }
    if (problems.length) {
        throw new Error(
            `P7 datasets not pre-built (expected 2000 train + 200 validation). Run: node scripts/build-datasets.mjs\n  - ${problems.join("\n  - ")}`
        );
    }
}

function p7DatasetGuard(): Plugin {
    return {
        name: "p7-dataset-guard",
        // `pnpm build` — fail the production build if assets are absent/wrong.
        buildStart() {
            verifyP7Datasets();
        },
        // `pnpm dev` — fail server startup with the same actionable error.
        configureServer() {
            verifyP7Datasets();
        },
    };
}

function envFlag(value: string | undefined): boolean {
    return value?.trim().toLowerCase() === "true";
}

export default defineConfig(({ mode }) => {
    const env = loadEnv(mode, process.cwd(), "");
    const enableMultiplayer = envFlag(
        process.env.ENABLE_MULTIPLAYER ?? env.ENABLE_MULTIPLAYER
    );
    // Cloudflare Workers (and the multiplayer Nitro server) both serve from the
    // domain root. Set BASE_PATH only when hosting under a sub-path.
    const base = env.BASE_PATH || "/";

    return {
        base,
        define: {
            "import.meta.env.ENABLE_MULTIPLAYER":
                JSON.stringify(enableMultiplayer),
        },
        resolve: { tsconfigPaths: true },
        server: {
            allowedHosts: ["mlp.kuo.is"],
        },
        plugins: [
            p7DatasetGuard(),
            tailwindcss(),
            devtools(),
            tanstackStart(
                enableMultiplayer
                    ? undefined
                    : {
                          spa: {
                              enabled: true,
                              maskPath: "/",
                              prerender: { outputPath: "/index" },
                          },
                      }
            ),
            nitro({ preset: "node-server" }),
            viteReact(),
        ],
    };
});
