import { existsSync, readFileSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig } from "vite";
import type { Plugin } from "vite";
import { devtools } from "@tanstack/devtools-vite";

import { tanstackStart } from "@tanstack/react-start/plugin/vite";

import viteReact from "@vitejs/plugin-react";
import { nitro } from "nitro/vite";
import tailwindcss from "@tailwindcss/vite";

/* The P7 "CNN Lab" reads pre-built dataset assets from public/datasets/. They are
   generated by `node scripts/build-datasets.mjs`, NOT at build time. This guard
   refuses to start the dev server or build if any of the four datasets is missing
   or isn't the expected 2000-train + 200-validation split, so a mis-built or
   absent asset fails loudly with an actionable message instead of the net
   silently training on nothing/garbage. */
const P7_DATASET_IDS = ["mnist", "fashion", "kmnist", "cifar10"];

function verifyP7Datasets(): void {
  const root = dirname(fileURLToPath(import.meta.url));
  const dir = join(root, "public", "datasets");
  const problems: string[] = [];
  for (const id of P7_DATASET_IDS) {
    const jsonPath = join(dir, `${id}.json`);
    const binPath = join(dir, `${id}.bin.gzip`);
    if (!existsSync(jsonPath) || !existsSync(binPath)) {
      problems.push(`${id}: missing ${id}.json and/or ${id}.bin.gzip`);
      continue;
    }
    if (statSync(binPath).size === 0) {
      problems.push(`${id}: ${id}.bin.gzip is empty`);
      continue;
    }
    let manifest: { trainN?: number; valN?: number };
    try {
      manifest = JSON.parse(readFileSync(jsonPath, "utf8"));
    } catch (e) {
      problems.push(`${id}: ${id}.json is not valid JSON (${(e as Error).message})`);
      continue;
    }
    if (manifest.trainN !== 2000 || manifest.valN !== 200) {
      problems.push(
        `${id}: wrong split (trainN=${manifest.trainN}, valN=${manifest.valN}; expected 2000 + 200)`,
      );
    }
  }
  if (problems.length) {
    throw new Error(
      `P7 datasets not pre-built (expected 2000 train + 200 validation). Run: node scripts/build-datasets.mjs\n  - ${problems.join("\n  - ")}`,
    );
  }
}

function p7DatasetGuard(): Plugin {
  return {
    name: "p7-dataset-guard",
    // `pnpm build` — fail the production build if assets are absent/wrong.
    buildStart() {
      verifyP7Datasets();
    },
    // `pnpm dev` — fail server startup with the same actionable error.
    configureServer() {
      verifyP7Datasets();
    },
  };
}

const config = defineConfig({
    resolve: { tsconfigPaths: true },
    server: {
        allowedHosts: ["mlp.kuo.is"],
    },
    plugins: [
        p7DatasetGuard(),
        tailwindcss(),
        devtools(),
        tanstackStart(),
        // The node-server preset already externalizes node_modules and traces
        // native bindings (better-sqlite3, @prisma) into .output/server/node_modules.
        // Passing a custom rollupConfig.external clobbers Nitro's own rollup config
        // and externalizes the Nitro runtime itself, producing a stub app that 404s
        // every route ("stub implementation will be used" warning). Leave it default.
        nitro(),
        viteReact(),
    ],
});

export default config;
